import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider } from "./providers/StoreProvider";
import ToasterProvider from "./providers/ToasterProvider";
import AuthProvider from "./providers/authProvider";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ToasterProvider />
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
